#!/bin/bash

# for each url in urlList.txt assign it to $1

for o in `cat urlList.txt`
do 
	OUTPUT=`python urlLast.py $o`
	echo $o
	echo $OUTPUT.txt
	#pandoc -s --no-wrap -f html -t markdown $0 | python ConvertMarkdownAsciidoc.py > $OUTPUT.txt
done
